version: '3'

services:
  pg:
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
      - pg:/var/lib/postgresql/data
    expose:
      - 5432

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    volumes:
      - pgadmin:/var/lib/pgadmin
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.pgadmin.rule=Host(`pgadmin.wordguess.ru`)'
      - 'traefik.http.routers.pgadmin.entryPoints=webSecure'
      - 'traefik.http.routers.pgadmin.tls.certResolver=myResolver'

  model:
    image: xalvaine/guess-model:${MODEL_VERSION}
    working_dir: /home/app

  backend_migrations:
    depends_on:
      - pg
    image: xalvaine/guess-backend:${BACKEND_VERSION}
    env_file:
      - .env
    command: yarn ci:orm:migration:run
    working_dir: /home/app
    profiles:
      - backend_migrations

  backend:
    restart: always
    depends_on:
      - pg
    image: xalvaine/guess-backend:${BACKEND_VERSION}
    env_file:
      - .env
    environment:
      VERSION: ${BACKEND_VERSION}
      WORD_GUESS_ENDPOINT: http://model:8000/similarity
      NEST_ADDRESS: 0.0.0.0
    working_dir: /home/app
    expose:
      - 8000
    command: yarn start:prod
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.backend.rule=Host(`backend.wordguess.ru`)'
      - 'traefik.http.routers.backend.entryPoints=webSecure'
      - 'traefik.http.routers.backend.tls.certResolver=myResolver'

  traefik:
    image: traefik:v2.8
    container_name: traefik
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedByDefault=false'
      - '--entryPoints.webSecure.address=:443'
      - '--certificatesResolvers.myResolver.acme.tlsChallenge=true'
      - '--certificatesResolvers.myResolver.acme.email=feedback@coffilation.ru'
      - '--certificatesResolvers.myResolver.acme.storage=/letsencrypt/acme.json'
    ports:
      - '8080:8080'
      - '443:443'
    volumes:
      - letsencrypt:/letsencrypt
      - '/var/run/docker.sock:/var/run/docker.sock:ro'

volumes:
  pg:
  pgadmin:
  letsencrypt:
